// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: shorturl.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ShortenBatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchItem) Reset() {
	*x = ShortenBatchItem{}
	mi := &file_shorturl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchItem) ProtoMessage() {}

func (x *ShortenBatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchItem.ProtoReflect.Descriptor instead.
func (*ShortenBatchItem) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenBatchItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponseItem) Reset() {
	*x = ShortenBatchResponseItem{}
	mi := &file_shorturl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponseItem) ProtoMessage() {}

func (x *ShortenBatchResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponseItem.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponseItem) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenBatchResponseItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ShortenBatchItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_shorturl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenBatchRequest) GetItems() []*ShortenBatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*ShortenBatchResponseItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_shorturl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenBatchResponse) GetItems() []*ShortenBatchResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_shorturl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{6}
}

func (x *URL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type UserUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URL                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUrlsResponse) Reset() {
	*x = UserUrlsResponse{}
	mi := &file_shorturl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsResponse) ProtoMessage() {}

func (x *UserUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsResponse.ProtoReflect.Descriptor instead.
func (*UserUrlsResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{7}
}

func (x *UserUrlsResponse) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUserUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserUrlsRequest) Reset() {
	*x = DeleteUserUrlsRequest{}
	mi := &file_shorturl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserUrlsRequest) ProtoMessage() {}

func (x *DeleteUserUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserUrlsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserUrlsRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserUrlsRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_shorturl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{9}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int64                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int64                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_shorturl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{10}
}

func (x *StatsResponse) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

type RedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectRequest) Reset() {
	*x = RedirectRequest{}
	mi := &file_shorturl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRequest) ProtoMessage() {}

func (x *RedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRequest.ProtoReflect.Descriptor instead.
func (*RedirectRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{11}
}

func (x *RedirectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_shorturl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_shorturl_proto_rawDescGZIP(), []int{12}
}

func (x *RedirectResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_shorturl_proto protoreflect.FileDescriptor

const file_shorturl_proto_rawDesc = "" +
	"\n" +
	"\x0eshorturl.proto\x12\bshorturl\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\x0eShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\x0fShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\\\n" +
	"\x10ShortenBatchItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"^\n" +
	"\x18ShortenBatchResponseItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"G\n" +
	"\x13ShortenBatchRequest\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.shorturl.ShortenBatchItemR\x05items\"P\n" +
	"\x14ShortenBatchResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".shorturl.ShortenBatchResponseItemR\x05items\"E\n" +
	"\x03URL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"5\n" +
	"\x10UserUrlsResponse\x12!\n" +
	"\x04urls\x18\x01 \x03(\v2\r.shorturl.URLR\x04urls\"6\n" +
	"\x15DeleteUserUrlsRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\tR\tshortUrls\"\a\n" +
	"\x05Empty\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x03R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x03R\x05users\"!\n" +
	"\x0fRedirectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x10RedirectResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xbe\x04\n" +
	"\x10ShortenerService\x12W\n" +
	"\aPostURL\x12\x18.shorturl.ShortenRequest\x1a\x19.shorturl.ShortenResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/shorten\x12p\n" +
	"\x10ShortenBatchPost\x12\x1d.shorturl.ShortenBatchRequest\x1a\x1e.shorturl.ShortenBatchResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/shorten/batch\x12P\n" +
	"\bRedirect\x12\x19.shorturl.RedirectRequest\x1a\x1a.shorturl.RedirectResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/{id}\x12O\n" +
	"\bUserUrls\x12\x0f.shorturl.Empty\x1a\x1a.shorturl.UserUrlsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/user/urls\x12d\n" +
	"\x0eDeleteUserUrls\x12\x1f.shorturl.DeleteUserUrlsRequest\x1a\x0f.shorturl.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/user/urls/delete\x12V\n" +
	"\rInternalStats\x12\x0f.shorturl.Empty\x1a\x17.shorturl.StatsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/internal/statsB\x10Z\x0eshorturl/protob\x06proto3"

var (
	file_shorturl_proto_rawDescOnce sync.Once
	file_shorturl_proto_rawDescData []byte
)

func file_shorturl_proto_rawDescGZIP() []byte {
	file_shorturl_proto_rawDescOnce.Do(func() {
		file_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shorturl_proto_rawDesc), len(file_shorturl_proto_rawDesc)))
	})
	return file_shorturl_proto_rawDescData
}

var file_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_shorturl_proto_goTypes = []any{
	(*ShortenRequest)(nil),           // 0: shorturl.ShortenRequest
	(*ShortenResponse)(nil),          // 1: shorturl.ShortenResponse
	(*ShortenBatchItem)(nil),         // 2: shorturl.ShortenBatchItem
	(*ShortenBatchResponseItem)(nil), // 3: shorturl.ShortenBatchResponseItem
	(*ShortenBatchRequest)(nil),      // 4: shorturl.ShortenBatchRequest
	(*ShortenBatchResponse)(nil),     // 5: shorturl.ShortenBatchResponse
	(*URL)(nil),                      // 6: shorturl.URL
	(*UserUrlsResponse)(nil),         // 7: shorturl.UserUrlsResponse
	(*DeleteUserUrlsRequest)(nil),    // 8: shorturl.DeleteUserUrlsRequest
	(*Empty)(nil),                    // 9: shorturl.Empty
	(*StatsResponse)(nil),            // 10: shorturl.StatsResponse
	(*RedirectRequest)(nil),          // 11: shorturl.RedirectRequest
	(*RedirectResponse)(nil),         // 12: shorturl.RedirectResponse
}
var file_shorturl_proto_depIdxs = []int32{
	2,  // 0: shorturl.ShortenBatchRequest.items:type_name -> shorturl.ShortenBatchItem
	3,  // 1: shorturl.ShortenBatchResponse.items:type_name -> shorturl.ShortenBatchResponseItem
	6,  // 2: shorturl.UserUrlsResponse.urls:type_name -> shorturl.URL
	0,  // 3: shorturl.ShortenerService.PostURL:input_type -> shorturl.ShortenRequest
	4,  // 4: shorturl.ShortenerService.ShortenBatchPost:input_type -> shorturl.ShortenBatchRequest
	11, // 5: shorturl.ShortenerService.Redirect:input_type -> shorturl.RedirectRequest
	9,  // 6: shorturl.ShortenerService.UserUrls:input_type -> shorturl.Empty
	8,  // 7: shorturl.ShortenerService.DeleteUserUrls:input_type -> shorturl.DeleteUserUrlsRequest
	9,  // 8: shorturl.ShortenerService.InternalStats:input_type -> shorturl.Empty
	1,  // 9: shorturl.ShortenerService.PostURL:output_type -> shorturl.ShortenResponse
	5,  // 10: shorturl.ShortenerService.ShortenBatchPost:output_type -> shorturl.ShortenBatchResponse
	12, // 11: shorturl.ShortenerService.Redirect:output_type -> shorturl.RedirectResponse
	7,  // 12: shorturl.ShortenerService.UserUrls:output_type -> shorturl.UserUrlsResponse
	9,  // 13: shorturl.ShortenerService.DeleteUserUrls:output_type -> shorturl.Empty
	10, // 14: shorturl.ShortenerService.InternalStats:output_type -> shorturl.StatsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_shorturl_proto_init() }
func file_shorturl_proto_init() {
	if File_shorturl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shorturl_proto_rawDesc), len(file_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturl_proto_goTypes,
		DependencyIndexes: file_shorturl_proto_depIdxs,
		MessageInfos:      file_shorturl_proto_msgTypes,
	}.Build()
	File_shorturl_proto = out.File
	file_shorturl_proto_goTypes = nil
	file_shorturl_proto_depIdxs = nil
}
